---
deployment:
  tasks:
  - export REPOPATH=$HOME/public_html/stvaldivia
  - cd $REPOPATH && /home/stvaldivia/virtualenv/stvaldivia/3.9/bin/pip install -r requirements.txt -q 2>/dev/null || true
  - echo "Deploy OK"
